[package]
name = "nuts-rs"
version = "0.16.1"
authors = [
  "Adrian Seyboldt <adrian.seyboldt@gmail.com>",
  "PyMC Developers <pymc.devs@gmail.com>",
]
edition = "2024"
license = "MIT"
repository = "https://github.com/pymc-devs/nuts-rs"
keywords = ["statistics", "bayes"]
description = "Sample from unnormalized densities using Hamiltonian MCMC"

[profile.bench]
debug = true
lto = "fat"
opt-level = 2
codegen-units = 1

[dependencies]
rand = { version = "0.9.0", features = ["small_rng"] }
rand_distr = "0.5.0"
itertools = "0.14.0"
thiserror = "2.0.3"
rand_chacha = "0.9.0"
anyhow = "1.0.72"
faer = { version = "0.22.6", default-features = false, features = ["linalg"] }
pulp = "0.21.4"
rayon = "1.10.0"
zarrs = { version = "0.21.0", features = [
  "filesystem",
  "gzip",
  "sharding",
  "async",
], optional = true }
ndarray = { version = "0.16.1", optional = true }
nuts-derive = { path = "./nuts-derive" }
nuts-storable = { path = "./nuts-storable" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["rt"], optional = true }

[dev-dependencies]
proptest = "1.6.0"
pretty_assertions = "1.4.0"
criterion = "0.7.0"
nix = { version = "0.30.0", features = ["sched"] }
approx = "0.5.1"
equator = "0.4.2"
serde_json = "1.0"
ndarray = "0.16.1"
tempfile = "3.0"
zarrs_object_store = "0.4.3"
object_store = "0.12.0"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread"] }

[features]
zarr = ["dep:zarrs", "dep:tokio"]
ndarray = ["dep:ndarray"]

[[bench]]
name = "sample"
harness = false

[workspace]
