[package]
name = "nuts-rs"
version = "0.1.0"
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/aseyboldt/nuts-rs"
keywords = ["statistics", "bayes"]

[profile.release]
debug = true
lto = "fat"
opt-level = 3
codegen-units = 1

[profile.bench]
# panic = "abort"
debug = true
lto = "fat"
opt-level = 3
codegen-units = 1

[dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
rand_distr = "0.4.3"
multiversion = "0.6.1"
itertools = "0.10.3"
#flume = "0.10.9"
crossbeam = "0.8.1"
thiserror = "1.0.31"
rayon = "1.5.3"
ndarray = "0.15.4"

[dev-dependencies]
proptest = "1.0.0"
pretty_assertions = "1.2.1"
criterion = "0.3.5"
nix = "0.24.1"
approx = "0.5.1"
#ndarray = "0.15.4"

[[bench]]
name = "sample"
harness = false

[features]
nightly = ["simd_support"]

simd_support = []
