[package]
name = "nuts-rs"
version = "0.1.0"
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
panic = "abort"
debug = true
lto = "fat"

[profile.bench]
panic = "abort"
debug = true
#lto = "fat"

[dependencies]
rand = "0.8.4"
rand_distr = "0.4.2"
#tvm = { path = "../tvm/rust/tvm" }
multiversion = "0.6.1"
rayon = "1.5.1"
itertools = "0.10.1"

[dependencies.ndarray]
version = "0.15.3"
features = ["rayon"]

[dev-dependencies]
proptest = "1.0.0"
pretty_assertions = "1.0.0"
criterion = "0.3.3"

[[bench]]
name = "sample"
harness = false
