[package]
name = "nuts-rs"
version = "0.1.0"
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
panic = "abort"
debug = true
lto = "fat"

[profile.bench]
rustflags = "-C target-cpu=native"
panic = "abort"
debug = true
lto = "fat"


[dependencies]
rand = "0.7"
rand_distr = "0.3"

[dev-dependencies]
proptest = "0.10.1"
pretty_assertions = "0.6.1"
criterion = "0.3"

[[bench]]
name = "sample"
harness = false
